name: mighty_mood
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #BASE
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  intl: ^0.18.0
  flutter_vector_icons: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.2.0
  flashy_tab_bar2: ^0.0.6

  #STATE MANAGEMENT
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5

  #DATABASE
  sqflite: ^2.2.4+1
  shared_preferences: ^2.0.17

  #CHART
  fl_chart: ^0.60.0

  #OTHER
  fluttertoast: 8.1.2
  emoji_picker_flutter: ^1.5.2
  emoji_alert: ^1.1.0
  record: ^4.4.4
  image_picker: ^0.8.6+2
  file_picker: ^5.2.5
  just_audio: ^0.9.31
  collection: ^1.17.1
  photo_view: ^0.14.0

  #GAME
  provider: ^6.0.5
  animated_text_kit: ^4.2.2

dependency_overrides:
  collection: ^1.17.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/images/
    - asset/game/
